CAN_PCM_ID = 0
CAN_PDP_ID = 0
CAN_ID_VICTOR_FRONT_LEFT = 0
CAN_ID_VICTOR_FRONT_RIGHT = 1
CAN_ID_VICTOR_REAR_LEFT = 2
CAN_ID_VICTOR_REAR_RIGHT = 3

BACK_LIFT_SOLENOID_PCM_PORT = 0
FRONT_LIFT_SOLENOID_PCM_PORT = 1

USB_PORT_DRIVER_ONE = 0
USB_PORT_DRIVER_TWO = 1

BUTTON_LEFT_BUMPER = 5
BUTTON_RIGHT_BUMPER = 6

AXIS_LEFT_X = 0
AXIS_LEFT_Y = 1