CAN_PCM_ID = 0
CAN_PDP_ID = 0

CAN_REV_HATCH_ANGLE = 0

BACK_LIFT_SOLENOID_PCM_PORT = 0
FRONT_LIFT_SOLENOID_PCM_PORT = 1
HATCH_LAUNCHER_PCM_PORT = 2


USB_PORT_DRIVER_ONE = 0
USB_PORT_DRIVER_TWO = 1

BUTTON_A = 1
BUTTON_LEFT_BUMPER = 5
BUTTON_RIGHT_BUMPER = 6

AXIS_LEFT_Y = 1