CAN_PCM_ID = 0
CAN_PDP_ID = 0
CAN_ID_VICTOR_FRONT_LEFT = 0
CAN_ID_VICTOR_FRONT_RIGHT = 1
CAN_ID_VICTOR_REAR_LEFT = 2
CAN_ID_VICTOR_REAR_RIGHT = 3
CAN_ID_VICTOR_BAND_SPINNER = 4

CAN_REV_HATCH_ANGLE = 1

BACK_LIFT_SOLENOID_PCM_PORT = 5
FRONT_LIFT_SOLENOID_PCM_PORT = 6
HATCH_LAUNCHER_PCM_PORT = 7

HATCH_ARM_SPEED_REDUCTION = 1

USB_PORT_DRIVER_ONE = 0
USB_PORT_DRIVER_TWO = 1

BUTTON_A = 1
BUTTON_Y = 4
BUTTON_LEFT_BUMPER = 5
BUTTON_RIGHT_BUMPER = 6

AXIS_LEFT_X = 0
AXIS_LEFT_Y = 1
AXIS_LEFT_TRIGGER = 2
AXIS_RIGHT_TRIGGER = 3

DIO_PORT_CARGO_MOTOR_STOPPER = 0
